### ISSUE TITLE
老哥，后后续嘛？思路是什么？

### ISSUE THREAD

**Issue by dfjx** [wusfen/vue-ie#1]
RT求教

**Comment by wushufen** [comment]
你可以关注下我的这个项目，这个是独立的兼容ie的mvvm框架，兼容 vue 语法。基本完成，不过还没有文档
https://github.com/wusfen/vm
兼容原理
1：method -> $fn(){ method();  vm.$foceUpdate() }
2:  对一些异步的函数进行复写，注入 $foceUpdate 。如 ajax, setTimeout 等

**Comment by wushufen** [comment]
这个项目主要是想以打补丁的方式支持vue下低版本的浏览器中运行。只是现在需要兼容ie的需求不那么强烈了。

**Comment by dfjx** [comment]
> 你可以关注下我的这个项目，这个是独立的兼容ie的mvvm框架，兼容 vue 语法。基本完成，不过还没有文档
> https://github.com/wusfen/vm
> 兼容原理
> 1：method -> $fn(){ method(); vm.$foceUpdate() }
> 2: 对一些异步的函数进行复写，注入 $foceUpdate 。如 ajax, setTimeout 等

这个框架兼容的vue版本是哪个？

**Comment by wushufen** [comment]
> > 你可以关注下我的这个项目，这个是独立的兼容ie的mvvm框架，兼容 vue 语法。基本完成，不过还没有文档
> > https://github.com/wusfen/vm
> > 兼容原理
> > 1：method -> $fn(){ method(); vm.$foceUpdate() }
> > 2: 对一些异步的函数进行复写，注入 $foceUpdate 。如 ajax, setTimeout 等
> 
> 这个框架兼容的vue版本是哪个？

2.0 大部分功能。不过还不支持 vue 单文件
